version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - apt-get update
      - apt-get install -y maven
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/**